apiVersion: v1
kind: Pod
metadata:
   name: apache-pod
   labels:
      app: apache-pod

spec:
   containers:
   - name: apache-container01
     image: sonalnikam/hello-apache:latest
     ports:
     - containerPort: 80
       hostIP: 3.234.209.211
       hostPort: 6379

---
kind: Service
apiVersion: v1
metadata:
  name: apache-service
spec:
  type: ClusterIP
  selector:
    app: apache-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 3.234.209.211


